name: Build Windows

on:
  push:
    branches: [ "features/github-actions" ]

jobs:
  msys2-ucrt64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          mingw-w64-x86_64-SDL2
          mingw-w64-x86_64-SDL2_mixer
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: make clean
      run: make clean
    - name: make
      run: make desktop-opengl
    - uses: actions/upload-artifact@v4
      with:
        name: dist
        path: .
