name: Build Windows

on:
  push:
    branches: [ "features/github-actions" ]

jobs:
  build-windows-msys2:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          git
          make
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-glew
          mingw-w64-x86_64-SDL2
          mingw-w64-x86_64-SDL2_mixer
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: make clean
      run: make clean
    - name: make lua
      run: cd ./libs/lua && make a CFLAGS+=-DLUA_USE_LONGJUMP
    - name: make
      run: make desktop-opengl
    - name: Copy assets
      run: cp -r assets ./build/bin
    - name: Copy dlls
      run: cp /mingw64/bin/SDL2.dll /mingw64/bin/SDL2_mixer.dll /mingw64/bin/glew32.dll /mingw64/bin/libmpg123-0.dll /mingw64/bin/libopusfile-0.dll /mingw64/bin/libogg-0.dll /mingw64/bin/libopus-0.dll ./build/bin
    - name: Package artifacts
      uses: actions/upload-artifact@v4
      with:
        name: brassengine-windows64
        path: ./build/bin
