name: Generate Docs

on:
  push:
    branches:
      - 'generate-docs'

jobs:
  generate-docs:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          git
          make
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: leafo/gh-actions-lua@v9
    - uses: leafo/gh-actions-luarocks@v4

    # Install some package
    - name: install a module
      run: luarocks install ldoc

    - name: make docs
      run: make docsclean && make docs
