name: Generate Docs

on:
  push:
    branches:
      - 'generate-docs'

jobs:
  generate-docs:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          git
          make
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-lua
          mingw-w64-x86_64-lua-luarocks
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Create temp dir
      run: |
        mkdir -p D:/a/_temp/msys64/home/runneradmin/.luarocks/lib/lua/5.4
        mkdir -p D:/a/_temp/msys64/home/runneradmin/.luarocks/lib/luarocks/rocks-5.4/markdown/0.32-2/lib
        mkdir -p D:/a/_temp/msys64/home/runneradmin/.luarocks/lib/luarocks/rocks-5.4/luafilesystem/1.8.0-1/lua
        mdkir -p D:/a/_temp/msys64/home/runneradmin/.luarocks/lib/luarocks/rocks-5.4/penlight/1.13.1-1/lib
        mkdir -p D:/a/_temp/msys64/home/runneradmin/.luarocks/share/lua/5.4
    - name: Install ldoc
      run: luarocks install --local ldoc
    - name: make docs
      run: make docsclean && make docs
