name: Generate Docs

on:
  push:
    branches:
      - 'generate-docs'

jobs:
  generate-docs:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          git
          make
          mingw-w64-x86_64-lua
          mingw-w64-x86_64-lua-luarocks
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install markdown
      run: luarocks install markdown
    - name: Install ldoc
      run: luarocks install ldoc
    - name: make docs
      run: make docsclean && make docs
