name: Generate Docs

on:
  push:
    branches:
      - 'generate-docs'

jobs:
  generate-docs:
    runs-on: linux-latest
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: leafo/gh-actions-lua@v9
    - uses: leafo/gh-actions-luarocks@v4

    # Install some package
    - name: Install LDoc
      run: luarocks install ldoc

    - name: make docs
      run: make docsclean && make docs

    - uses: actions/upload-artifact@master
      with:
        name: docs
        path: docs